baseURL = "http://leyluiaa.github.io/"
languageCode = "fr-FR"
title = "Le rep√®re de LeyluIAA"

[Params]
    logo = "img/srm.png"
    favicon = "img/favicon.ico"

[Author]
    twitter = "leyluiaa"
    github = "LeyluIAA"
    handle = "LeyluIAA"
